/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContextRouteImport } from './routes/context'
import { Route as CyclesRouteImport } from './routes/cycles'
import { Route as EventsRouteImport } from './routes/events'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PackRouteImport } from './routes/pack'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as RoutingRouteImport } from './routes/routing'
import { Route as SpecRouteImport } from './routes/spec'
import { Route as TeammatesRouteImport } from './routes/teammates'
import { Route as ApiAgentOsCatalogRouteImport } from './routes/api/agent-os/catalog'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContextRoute = ContextRouteImport.update({
  id: '/context',
  path: '/context',
  getParentRoute: () => rootRouteImport,
} as any)
const CyclesRoute = CyclesRouteImport.update({
  id: '/cycles',
  path: '/cycles',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PackRoute = PackRouteImport.update({
  id: '/pack',
  path: '/pack',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutingRoute = RoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecRoute = SpecRouteImport.update({
  id: '/spec',
  path: '/spec',
  getParentRoute: () => rootRouteImport,
} as any)
const TeammatesRoute = TeammatesRouteImport.update({
  id: '/teammates',
  path: '/teammates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentOsCatalogRoute = ApiAgentOsCatalogRouteImport.update({
  id: '/api/agent-os/catalog',
  path: '/api/agent-os/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/context': typeof ContextRoute
  '/cycles': typeof CyclesRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/pack': typeof PackRoute
  '/prompts': typeof PromptsRoute
  '/routing': typeof RoutingRoute
  '/spec': typeof SpecRoute
  '/teammates': typeof TeammatesRoute
  '/api/agent-os/catalog': typeof ApiAgentOsCatalogRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/context': typeof ContextRoute
  '/cycles': typeof CyclesRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/pack': typeof PackRoute
  '/prompts': typeof PromptsRoute
  '/routing': typeof RoutingRoute
  '/spec': typeof SpecRoute
  '/teammates': typeof TeammatesRoute
  '/api/agent-os/catalog': typeof ApiAgentOsCatalogRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/context': typeof ContextRoute
  '/cycles': typeof CyclesRoute
  '/events': typeof EventsRoute
  '/login': typeof LoginRoute
  '/pack': typeof PackRoute
  '/prompts': typeof PromptsRoute
  '/routing': typeof RoutingRoute
  '/spec': typeof SpecRoute
  '/teammates': typeof TeammatesRoute
  '/api/agent-os/catalog': typeof ApiAgentOsCatalogRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/context'
    | '/cycles'
    | '/events'
    | '/login'
    | '/pack'
    | '/prompts'
    | '/routing'
    | '/spec'
    | '/teammates'
    | '/api/agent-os/catalog'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/context'
    | '/cycles'
    | '/events'
    | '/login'
    | '/pack'
    | '/prompts'
    | '/routing'
    | '/spec'
    | '/teammates'
    | '/api/agent-os/catalog'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/context'
    | '/cycles'
    | '/events'
    | '/login'
    | '/pack'
    | '/prompts'
    | '/routing'
    | '/spec'
    | '/teammates'
    | '/api/agent-os/catalog'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContextRoute: typeof ContextRoute
  CyclesRoute: typeof CyclesRoute
  EventsRoute: typeof EventsRoute
  LoginRoute: typeof LoginRoute
  PackRoute: typeof PackRoute
  PromptsRoute: typeof PromptsRoute
  RoutingRoute: typeof RoutingRoute
  SpecRoute: typeof SpecRoute
  TeammatesRoute: typeof TeammatesRoute
  ApiAgentOsCatalogRoute: typeof ApiAgentOsCatalogRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/context': {
      id: '/context'
      path: '/context'
      fullPath: '/context'
      preLoaderRoute: typeof ContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycles': {
      id: '/cycles'
      path: '/cycles'
      fullPath: '/cycles'
      preLoaderRoute: typeof CyclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pack': {
      id: '/pack'
      path: '/pack'
      fullPath: '/pack'
      preLoaderRoute: typeof PackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routing': {
      id: '/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof RoutingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spec': {
      id: '/spec'
      path: '/spec'
      fullPath: '/spec'
      preLoaderRoute: typeof SpecRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teammates': {
      id: '/teammates'
      path: '/teammates'
      fullPath: '/teammates'
      preLoaderRoute: typeof TeammatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent-os/catalog': {
      id: '/api/agent-os/catalog'
      path: '/api/agent-os/catalog'
      fullPath: '/api/agent-os/catalog'
      preLoaderRoute: typeof ApiAgentOsCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContextRoute: ContextRoute,
  CyclesRoute: CyclesRoute,
  EventsRoute: EventsRoute,
  LoginRoute: LoginRoute,
  PackRoute: PackRoute,
  PromptsRoute: PromptsRoute,
  RoutingRoute: RoutingRoute,
  SpecRoute: SpecRoute,
  TeammatesRoute: TeammatesRoute,
  ApiAgentOsCatalogRoute: ApiAgentOsCatalogRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
